flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:eklinkhammer/neural-algorithms
    commit: master
extra-deps:
- hnn-0.3
- normaldistribution-1.1.0.3
resolver: lts-7.15
